insight-mainnet:
  build: .
  dockerfile: Dockerfile
  container_name: insight-mainnet
  ports:
    - "12100:3002"   # API endpoint
    - "12101:28331" # ZMQ port
  volumes:
    - ../blockchain-data:/home/insight/blockchain-data
    #- ~/tmp:/home/insight/blockchain-data
  restart: always
