insight-mainnet:
  build: .
  dockerfile: Dockerfile
  container_name: insight-mainnet
  ports:
    - "3002:3002"   # API endpoint
    - "28331:28331" # ZMQ port
  volumes:
    - /mnt/data/bitcoin.com/blockchain-data/insight-mainnet/blockchain-data:/home/insight/blockchain-data
    #- ~/tmp:/home/insight/blockchain-data
  restart: always
