insight-testnet:
  build: .
  dockerfile: Dockerfile
  #image: christroutner/insight-bch-0.20.4
  container_name: insight-testnet
  ports:
    - "3001:3001"   # API endpoint
    - "28331:28331" # ZMQ port
  volumes:
    - /mnt/dev_qa_insight_api_v20_nyc1/blockchain-data:/home/insight/blockchain-data
    #- ~/tmp:/home/insight/blockchain-data
  restart: always
