insight-testnet:
  build: .
  dockerfile: Dockerfile
  container_name: insight-testnet
  ports:
    - "13100:3001"   # API endpoint
    - "13101:28331" # ZMQ port
  volumes:
    - ../blockchain-data:/home/insight/blockchain-data
    #- ~/tmp:/home/insight/blockchain-data
  restart: always
