#!/bin/bash

# Ensure the config file is in place
cp config/mainnet-example/bitcoin.conf ~/blockchain-data-insight/

# Run the insight-bch Docker image
docker container run --name insight-bch -d -v ~/blockchain-data-insight:/home/insight/blockchain-data -p 3002:3002 --rm insight-bch
